name: Python generator

on:
  push:
    paths:
      - "docs/*.md"

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ github.ref }}
      - run: pip install mkdocs-material jupyter nbconvert mkdocs-jupyter
      - run: mkdocs gh-deploy --force
