name: Python generator

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install MD-Models
        run: cargo install --git https://github.com/JR-1991/md-models.git

      - name: Run the generation pipeline
        run: md-models pipeline -i gen.toml

      - name: Format the generated code
        uses: chartboost/ruff-action@v1
        with:
          changed-files: "true"
          args: "format"

      - name: "Pushing API"
        shell: "bash"
        run: |
          if [[ `git status --porcelain` ]]; then
              git add --all
              git config --global user.name 'MD-Models Bot'
              git config --global user.email 'mdmodels@bot.com'
              git commit -am "Pipeline update"
              git push
          else
            echo "Nothing changed!"
          fi
